server:
  port: 10001
  servlet:
    context-path: /cpirh-auth
spring:
  application:
    name: auth
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
  # redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 35.174.185.33
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 950831
    # 连接超时时间
    timeout: 10s
    pool:
      # 连接池最大连接数
      max-active: 50
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 60000ms
      # 连接池中的最大空闲连接
      max-idle: 10
      # 连接池中的最小空闲连接
      min-idle: 10
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 172800
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: 7200
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: simple-uuid
  # 前后端分离，不适应cookie
  is-read-cookie: false
  # 验证用户时从request的header中获去token
  is-read-header: true
  # 登陆时将token添加到response的header中
  is-write-header: true
  # 是否输出操作日志
  is-log: false
  # 是否输出版本信息
  is-print: false

knife4j:
  # 开启增强配置
  enable: true
  setting:
    enable-dynamic-parameter: true